---
- hosts: appservers
  user: root
  become: yes
  gather_facts: no
  connection: ssh
  
  vars_prompt:
    - name: package
      prompt: Which package you want to install?
      private: no
      
  tasks:
    - name: Installing the package "{{ package }}"
      yum:
       name: '{{ package }}'
       state: installed