--- # lookup plugin is evaluated on control machine
- hosts: all
  become: yes
  user: root
  connection: ssh
  gather_facts: no
  tasks:
    - debug: msg="Lookup  the SuperHero for BRUCE WAYNE  {{ lookup('csvfile', 'Bruce_Wayne file=lookup.csv delimiter=,') }}"
    - debug: msg="The atomic number of Lithium is {{ lookup('csvfile', 'Li file=elements.csv delimiter=,') }}"
    - debug: msg="The atomic mass of Lithium is {{ lookup('csvfile', 'Li file=elements.csv delimiter=, col=2') }}" 
    - debug: msg="The value of home is {{ lookup('env','HOME') }}"