---
- hosts: all
  user: ansible
  become: yes
  gather_facts: no
  tasks:
   - block:
       - name: Create a file on remote servers
         file: 
            path: /tmp/ansible.test
            mode: 0644
            owner: root
            group: root

